services:
  backend:
    build:
      context: ./myproject
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./myproject:/app
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/pyramids_db

  frontend:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./myapp:/app
    depends_on:
      - backend

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pyramids_db

volumes:
  postgres_data:
