# Generated by Django 5.1.3 on 2024-11-08 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='price',
        ),
        migrations.RemoveField(
            model_name='refillrequest',
            name='quantity',
        ),
        migrations.AddField(
            model_name='medication',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refillrequest',
            name='date_requested',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
